# Generated by Django 3.0.5 on 2020-04-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('received', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Earnings',
            },
        ),
    ]
