# Generated by Django 3.0.7 on 2020-12-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='credit_card_ref',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('BO', 'Bonus'), ('AM', 'AlgoMania'), ('OT', 'Others'), ('UD', 'Udemy')], default='', max_length=4, verbose_name='category'),
        ),
    ]
