# Generated by Django 3.0.5 on 2020-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('UD', 'Udemy'), ('AG', 'AlgoMania'), ('SL', 'Salario')], default='', max_length=2, verbose_name='Source'),
            preserve_default=False,
        ),
    ]
