# Generated by Django 3.0.5 on 2020-04-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_credit_card_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardbills',
            options={'ordering': ['transaction_time', 'value'], 'verbose_name_plural': 'Credit Card Bills'},
        ),
        migrations.RenameField(
            model_name='creditcardbills',
            old_name='time',
            new_name='transaction_time',
        ),
        migrations.AlterField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('SL', 'Salario'), ('AG', 'AlgoMania'), ('UD', 'Udemy')], max_length=2, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('NUB', 'Nubank'), ('CAI', 'Caixa'), ('SAN', 'Santander'), ('BRD', 'Bradesco')], max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('BO', 'Bonus'), ('SL', 'Salary'), ('OT', 'Others'), ('UD', 'Udemy'), ('AM', 'AlgoMania')], default='', max_length=4, verbose_name='category'),
        ),
    ]
