# Generated by Django 3.0.7 on 2020-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201214_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='transaction_id',
            field=models.CharField(default='', max_length=50, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('CAI', 'Caixa'), ('SAN', 'Santander'), ('BRD', 'Bradesco'), ('NUB', 'Nubank')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('UD', 'Udemy'), ('AM', 'AlgoMania'), ('BO', 'Bonus'), ('OT', 'Others'), ('SL', 'Salary')], default='', max_length=4, verbose_name='category'),
        ),
    ]
