# Generated by Django 3.0.5 on 2020-04-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200424_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbills',
            name='charge_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('CAI', 'Caixa'), ('NUB', 'Nubank'), ('SAN', 'Santander'), ('BRD', 'Bradesco')], max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('AM', 'AlgoMania'), ('OT', 'Others'), ('SL', 'Salary'), ('BO', 'Bonus'), ('UD', 'Udemy')], default='', max_length=4, verbose_name='category'),
        ),
    ]
