# Generated by Django 3.0.5 on 2020-04-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200404_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('UD', 'Udemy'), ('SL', 'Salario'), ('AG', 'AlgoMania')], max_length=2, verbose_name='Source'),
        ),
    ]
