# Generated by Django 3.0.5 on 2020-04-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200424_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='credit_card_ref',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('NUB', 'Nubank'), ('BRD', 'Bradesco'), ('CAI', 'Caixa'), ('SAN', 'Santander')], max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('AM', 'AlgoMania'), ('SL', 'Salary'), ('UD', 'Udemy'), ('OT', 'Others'), ('BO', 'Bonus')], default='', max_length=4, verbose_name='category'),
        ),
    ]
