# Generated by Django 3.0.5 on 2020-04-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200406_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('AG', 'AlgoMania'), ('UD', 'Udemy'), ('SL', 'Salario')], max_length=2, verbose_name='Source'),
        ),
    ]
