# Generated by Django 3.0.5 on 2020-04-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200407_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('UD', 'Udemy'), ('BO', 'Bonus'), ('AM', 'AlgoMania'), ('OT', 'Others'), ('SL', 'Salary')], default='', max_length=4, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('SL', 'Salario'), ('AG', 'AlgoMania'), ('UD', 'Udemy')], max_length=2, verbose_name='Source'),
        ),
    ]
