# Generated by Django 3.0.5 on 2020-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200425_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditCardSummary',
            new_name='CreditCardInfo',
        ),
        migrations.AlterModelOptions(
            name='creditcardinfo',
            options={'verbose_name_plural': 'Credit Card Info'},
        ),
        migrations.AlterField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('SL', 'Salario'), ('AG', 'AlgoMania'), ('UD', 'Udemy')], max_length=2, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('BRD', 'Bradesco'), ('NUB', 'Nubank'), ('CAI', 'Caixa'), ('SAN', 'Santander')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('UD', 'Udemy'), ('AM', 'AlgoMania'), ('OT', 'Others'), ('BO', 'Bonus')], default='', max_length=4, verbose_name='category'),
        ),
    ]
