# Generated by Django 3.0.5 on 2020-04-25 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200425_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCardInfo',
        ),
        migrations.AddField(
            model_name='creditcardbills',
            name='closing_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='origin',
            field=models.CharField(choices=[('UD', 'Udemy'), ('SL', 'Salario'), ('AG', 'AlgoMania')], max_length=2, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('SAN', 'Santander'), ('BRD', 'Bradesco'), ('CAI', 'Caixa'), ('NUB', 'Nubank')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('BO', 'Bonus'), ('OT', 'Others'), ('UD', 'Udemy'), ('AM', 'AlgoMania')], default='', max_length=4, verbose_name='category'),
        ),
    ]
