# Generated by Django 3.0.5 on 2020-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200429_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardCategoryUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('UD', 'Udemy'), ('AM', 'AlgoMania'), ('BO', 'Bonus'), ('OT', 'Others'), ('SL', 'Salary')], default='', max_length=4, verbose_name='category'),
        ),
    ]
