# Generated by Django 3.0.5 on 2020-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200429_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardDateUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.TextField()),
                ('orig_transaction_date', models.DateField()),
                ('new_transaction_date', models.DateField()),
                ('new_closing_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('SAN', 'Santander'), ('NUB', 'Nubank'), ('CAI', 'Caixa'), ('BRD', 'Bradesco')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('UD', 'Udemy'), ('BO', 'Bonus'), ('AM', 'AlgoMania'), ('OT', 'Others'), ('SL', 'Salary')], default='', max_length=4, verbose_name='category'),
        ),
    ]
