# Generated by Django 3.0.5 on 2020-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200430_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcarddateupdate',
            old_name='new_transaction_date',
            new_name='new_payment_date',
        ),
        migrations.RenameField(
            model_name='creditcarddateupdate',
            old_name='orig_transaction_date',
            new_name='orig_transaction_time',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('NUB', 'Nubank'), ('SAN', 'Santander'), ('BRD', 'Bradesco'), ('CAI', 'Caixa')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('OT', 'Others'), ('UD', 'Udemy'), ('SL', 'Salary'), ('AM', 'AlgoMania'), ('BO', 'Bonus')], default='', max_length=4, verbose_name='category'),
        ),
    ]
