# Generated by Django 3.0.5 on 2020-04-30 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200430_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcarddateupdate',
            name='orig_payment_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('BRD', 'Bradesco'), ('SAN', 'Santander'), ('CAI', 'Caixa'), ('NUB', 'Nubank')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('OT', 'Others'), ('AM', 'AlgoMania'), ('UD', 'Udemy'), ('SL', 'Salary'), ('BO', 'Bonus')], default='', max_length=4, verbose_name='category'),
        ),
    ]
