# Generated by Django 3.0.5 on 2020-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200430_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddateupdate',
            name='orig_transaction_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('SAN', 'Santander'), ('CAI', 'Caixa'), ('BRD', 'Bradesco'), ('NUB', 'Nubank')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('UD', 'Udemy'), ('AM', 'AlgoMania'), ('BO', 'Bonus'), ('OT', 'Others')], default='', max_length=4, verbose_name='category'),
        ),
    ]
