# Generated by Django 3.0.5 on 2020-05-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200430_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('AM', 'AlgoMania'), ('OT', 'Others'), ('BO', 'Bonus'), ('UD', 'Udemy'), ('SL', 'Salary')], default='', max_length=4, verbose_name='category'),
        ),
    ]
