# Generated by Django 3.0.5 on 2020-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200506_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbills',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('SAN', 'Santander'), ('CAI', 'Caixa'), ('NUB', 'Nubank'), ('BRD', 'Bradesco')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('OT', 'Others'), ('BO', 'Bonus'), ('UD', 'Udemy'), ('AM', 'AlgoMania')], default='', max_length=4, verbose_name='category'),
        ),
    ]
