# Generated by Django 3.0.5 on 2020-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200727_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcarddateupdate',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('NUB', 'Nubank'), ('SAN', 'Santander'), ('CAI', 'Caixa'), ('BRD', 'Bradesco')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('BO', 'Bonus'), ('AM', 'AlgoMania'), ('OT', 'Others'), ('UD', 'Udemy'), ('SL', 'Salary')], default='', max_length=4, verbose_name='category'),
        ),
    ]
