# Generated by Django 3.0.5 on 2020-10-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200818_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbills',
            name='charge_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('NUB', 'Nubank'), ('CAI', 'Caixa'), ('SAN', 'Santander'), ('BRD', 'Bradesco')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('UD', 'Udemy'), ('BO', 'Bonus'), ('OT', 'Others'), ('AM', 'AlgoMania')], default='', max_length=4, verbose_name='category'),
        ),
    ]
