# Generated by Django 3.0.5 on 2020-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201008_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('BRD', 'Bradesco'), ('CAI', 'Caixa'), ('SAN', 'Santander'), ('NUB', 'Nubank')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('AM', 'AlgoMania'), ('UD', 'Udemy'), ('BO', 'Bonus'), ('OT', 'Others')], default='', max_length=4, verbose_name='category'),
        ),
    ]
