# Generated by Django 3.0.7 on 2020-11-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201008_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardbills',
            name='transaction_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank_account',
            field=models.CharField(choices=[('SAN', 'Santander'), ('NUB', 'Nubank'), ('CAI', 'Caixa'), ('BRD', 'Bradesco')], default='BRD', max_length=3, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='category',
            field=models.CharField(choices=[('SL', 'Salary'), ('AM', 'AlgoMania'), ('OT', 'Others'), ('BO', 'Bonus'), ('UD', 'Udemy')], default='', max_length=4, verbose_name='category'),
        ),
    ]
