name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run Tests
          run: coverage run manage.py test
          env:
            SECRET_KEY: test_secret_key

        - name: Execute Unit Tests and Publish Code Coverage
          uses: paambaati/codeclimate-action@v2.7.4
          env:
            CC_TEST_REPORTER_ID: 3751f89e3d9457b8c3955e300b41aa1ca5f8f2dd81469838d3ec68fcee2938ad
            SECRET_KEY: test_secret_key
          with:
            coverageCommand: coverage xml
            debug: false
